version: "3"
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./uwsgi.ini:/app/uwsgi.ini
    ports:
      - "5001:80"
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbit:5672
      - CELERY_RESULT_BACKEND=amqp://guest:guest@rabbit:5672
  rabbit:
    hostname: rabbit
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  worker:
    build:
      context: .
      dockerfile: Dockerfile_celery
    volumes:
      - ./app:/app
    links:
      - rabbit
    depends_on:
      - rabbit
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbit:5672
      - CELERY_RESULT_BACKEND=amqp://guest:guest@rabbit:5672
  # database:
  #   hostname: mongo
  #   image: mongo:latest
  #   ports:
  #     - "27018:27017"
