# FROM python:3.4-alpine
FROM python:3.7-alpine
ADD ./requirements.txt /app/requirements.txt
ADD ./app/ /app/
WORKDIR /app/
RUN pip install -r requirements.txt
ENTRYPOINT celery -A main.celery worker --concurrency=20 --loglevel=info